spring.application.name=Nom_de_votre_application
# Connexion à la base de donnée
# Force la connexion sécurisée
spring.datasource.url=lien_de_votre_connexion_a_la_bdd
spring.datasource.username=votre_utilisateur 
spring.datasource.password=mot_de_passe

# le driver postgres
spring.datasource.driver-class-name=driver_pour_postgre

# on dit à hibernat de ne pas toucher au tables existante
spring.jpa.hibernate.ddl-auto=none

# on enabel cette fonction pour voir les requetes sql dans le terminal pour le debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
