spring.application.name=shoppinglist
# Connexion à la base de donnée
# Force la connexion sécurisée
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.umefjfysypwktsmlvrhv
spring.datasource.password=ListesCourses.

# le driver postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# on dit à hibernat de ne pas toucher au tables existante
spring.jpa.hibernate.ddl-auto=none

# on enabel cette fonction pour voir les requetes sql dans le terminal pour le debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true